### ISSUE TITLE
how can create button same

### ISSUE THREAD

**Issue by J-Arji** [LeBzul/LBZSpinner#1]
hi 
very nice library 
how can create button like ?
[https://github.com/LeBzul/LBZSpinner/blob/master/example_images/spinner_gray.png](url)

**Comment by LeBzul** [comment]
Hi !
Thank for you comment. 👍

Just delete UITableviewDelegate method and all Dropdownlist method. Look this attachment example :
[LBZSpinner.txt](https://github.com/LeBzul/LBZSpinner/files/496128/LBZSpinner.txt)

(Rename to LBZSpinner.swift)

**Comment by J-Arji** [comment]
thank you :)
