### ISSUE TITLE
changeSelectedIndex not working!

### ISSUE THREAD

**Issue by Lithium-HD** [LeBzul/LBZSpinner#2]
Hi. thanks for the library
I have an issue on this method: "changeSelectedIndex"
it's not working as I expect. take a look at my code:

```
var lstTitles = [String]()
                if (self.lstScheduleGroups.count > 0) {
                    for item in self.lstScheduleGroups {
                        lstTitles.append((item.Title)!)
                    }
                    self.spinnerScheduleSubgroups.updateList(lstTitles)
                    if (lstTitles.count > 0) {
                        self.spinnerScheduleSubgroups.changeSelectedIndex(7) // the list contains 15 elements, and this number (7) is just a test to see if it's working or not
                    }
                }

```

what is the problem?

**Comment by LeBzul** [comment]
Hello ! 
Thank you for the bug report.

You can update method changeSelectedIndex by : 

```
func changeSelectedIndex(index:Int) {
    if list.count > index {
        selectedIndex = index
        text = list[selectedIndex]
        updateUI()

        if (delegate != nil) {
            delegate.spinnerChoose(self,index:selectedIndex, value: list[selectedIndex])
        }
    }
}
```

( I update this projet tonight. )

**Comment by Lithium-HD** [comment]
thanks for the quick answer. I had a suggestion for this too. it would be nice to have 2 values for each item of the spinner. one value for the title to show in the box and the other value for keeping its id,tag or whatever. anyway thanks again (y)

**Comment by LeBzul** [comment]
Thanks you to use my library !
Sorry, but I've not time to add feature on this library, I work on other project for now.
Maybe in future... For now, if you want add feature on this library, fork it ! ;-)
Make a pull request and I will add your work with with pleasure ! :)

**Comment by masthanl** [comment]
var Module = [Student]()
var ListItem = [String]()

var selectedspinnerName : LBZSpinner
/////
didload()
selectedspinnerName .append(ListItem )
/////////


/////////
func showName(){
          Module.count>0{
               for item in Module{
                     ListItem .append(item.Name)// Student name
                  }
                 selectedspinnerName.updateList(ListItem)
               if ListItem.count > 0{
                 selectedspinnerName.changeSelectedIndex[0]
              }
             }

}

class Student{

var Name : String

init(Name : String){
self.Name = Name
}
}
